name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: sudo apt update && sudo apt install -y libnetfilter-queue-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: GOARCH=arm64 GOOS=linux go build -v

    - name: Test
      run: GOARCH=arm64 GOOS=linux go test -v
